name: flutter_jvtd
description: flutter基础框架
version: 0.1.1
author: 陈磊
homepage: https://github.com/q200892907/flutter_jvtd.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.0

  flutter_jvtd_dialog:
    git:
      url: 'https://github.com/q200892907/flutter_jvtd_dialog.git'
      ref: 0.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # https://pub.dartlang.org/packages/fluttertoast
  # Android及iOS toast控件 用于提示信息
  fluttertoast: ^2.2.11

  # https://pub.dartlang.org/packages/url_launcher
  # 启动外部浏览器
  url_launcher: ^5.0.1

  # https://pub.dartlang.org/packages/shared_preferences
  # 本地数据缓存 Android（SharedPreferences）/iOS（NSUserDefaults）
  shared_preferences: ^0.4.0

  # https://pub.dartlang.org/packages/flutter_statusbar_manager
  # 状态栏管理
  flutter_statusbar_manager: ^1.0.2

  # https://pub.dartlang.org/packages/cached_network_image
  # 网络图片加载及缓存
  cached_network_image: ^0.5.1

  # https://pub.dartlang.org/packages/transparent_image
  # 透明图像库
  transparent_image: ^0.1.0

  # https://pub.flutter-io.cn/packages/flutter_redux
  # 状态管理
  flutter_redux: ^0.5.3

  # https://pub.dartlang.org/packages/connectivity
  # 网络连接
  connectivity: ^0.3.2

  # https://pub.dartlang.org/packages/fluro
  # 路由管理
  fluro: ^1.4.0

  # https://pub.dartlang.org/packages/flutter_swiper
  # 无限滚动视图
  flutter_swiper: ^1.1.4

  # 刷新加载
  pull_to_refresh: ^1.5.2

  # 键盘管理
  keyboard_actions: ^1.0.3

  # event_bus
  event_bus: ^1.0.3

  # webview
  webview_flutter: ^0.3.3+1

  # 加载动画库
  flutter_spinkit: ^3.1.0

  # 瀑布流
  flutter_staggered_grid_view: ^0.2.7

  # 选择器
  flutter_picker: ^1.0.7

  # html展示
  flutter_html: ^0.9.4

  # 拼音
  lpinyin: ^1.0.7

  # 悬停索引
  azlistview: ^0.1.0

  # rc4加密
  simple_rc4: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
